export const ADD_NEW_ITEM = 'ADD_NEW_ITEM';
export const UPDATE_ITEM = 'UPDATE_ITEM';
export const GET_CATEGORY_LIST = 'GET_CATEGORY_LIST';
export const GET_COURSE_LIST = 'GET_COURSE_LIST';

export const GET_PURCHASED_COURSE_LIST = 'GET_PURCHASED_COURSE_LIST';

export const GET_COMMENT_LIST = 'GET_COMMENT_LIST';